AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/Copyright:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MultilineMethodSignature:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
