AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 3.0
  Exclude:
    - 'test/**/test_*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
