AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 3.0

Style/Copyright:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/MissingElse:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
