name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUBY_VERSION: 3.3.6
  SIMPLECOV_THRESHOLD: 100

jobs:
  tests_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run TestsChecker
        run: ruby -r "./ci/tests_checker.rb" -e "::CI::TestsChecker.new.process"

  links_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run LinksChecker
        run: ruby -r "./ci/links_checker.rb" -e "::CI::LinksChecker.new.process"

  version_checker:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run VersionChecker
        run: ruby -r "./ci/version_checker.rb" -e "::CI::VersionChecker.new.process"

  readme_duplicates_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run ReadmeDuplicatesChecker
        run: ruby -r "./ci/readme_duplicates_checker.rb" -e "::CI::ReadmeDuplicatesChecker.new.process"

  readme_paths_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run ReadmePathsChecker
        run: ruby -r "./ci/readme_paths_checker.rb" -e "::CI::ReadmePathsChecker.new.process"

  duplicate_links_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run DuplicateLinksChecker
        run: ruby -r "./ci/duplicate_links_checker.rb" -e "::CI::DuplicateLinksChecker.new.process"

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.rb
      - name: Set up Ruby
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bundle install
      - name: Run RuboCop
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bundle exec rubocop ${{ steps.changed-files.outputs.all_changed_files }}

  tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: ${{ env.SIMPLECOV_THRESHOLD }}
